apiVersion: v1
kind: Service
metadata: 
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - name: drupal-ports
      protocol: TCP
      nodePort: 30095
      targetPort: 80
      port: 30095
