apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: drupal-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: drupal-mysql-secret 
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: drupal-mysql-secret 
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
              name: drupal-mysql
          volumeMounts:
            - name: pvc
              mountPath: /var/lib/mysql
              subPath: dbdata
      volumes:
        - name: pvc
          persistentVolumeClaim: 
            claimName: drupal-mysql-pvc