apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /web
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  volumeName: data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata: 
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    app: gop
  ports:
    - name: gop-ports
      protocol: TCP
      nodePort: 31200
      targetPort: 8080
      port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gop
  name: gop-fileserver
spec:
  containers:
    - name: gop
      image: kodekloud/fileserver
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: data-store
          mountPath: /web
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
