apiVersion: v1
kind: Service
metadata: 
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - name: drupal-ports
      protocol: TCP
      nodePort: 8080
      targetPort: 8080
      port: 8080
