apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
spec:
  containers:
    - name: gop
      image: kodekloud/fileserver
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: data-store
          mountPath: /web
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc