apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
type: Opaque
data: 
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl

---

apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  type: ClusterIP
  ports:
    - name: drupal-mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: drupal-mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: drupal-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: drupal-mysql-secret 
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: drupal-mysql-secret 
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
              name: drupal-mysql
          volumeMounts:
            - name: pvc
              mountPath: /var/lib/mysql
              subPath: dbdata
      volumes:
        - name: pvc
          persistentVolumeClaim: 
            claimName: drupal-mysql-pvc